spring.profiles.active: local

server:
#  port: 9443
  port: 9000
  ssl:
#    enabled: true
    enabled: false
    key-store: classpath:movie_park.p12
    key-store-password: password
    key-store-type: PKCS12

spring:
  datasource:
    prod:
      # real database
      url: url
      username: user
      password: password
      driverClassName: driver
    local:
      # localhost database in docker container
      url: jdbc:postgresql://localhost:5432/trade_center
      username: postgres
      password: movie_park_api_password
      driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        auto_quote_keyword: true
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

cache:
  seance_info:
    flush_timeout: 10
    flush_timeout_min: 2
    flush_timeout_max: 30
  rps:
    flush_timeout: 10
    lifetime: 120

# actuator
management:
  endpoints:
    web.base-path: /movie-park/service
#    web.exposure.include: env,info,health,httptrace,logfile,metrics,mappings
#  HEALTH ENDPOINT
  endpoint:
    health.show-details: always
  health.diskSpace.enabled: false
