spring.profiles.active: prod
spring:
  datasource:
    prod:
      # real database
      url: url
      username: user
      password: password
      driverClassName: driver
    dev:
      # localhost database in docker container
      url: jdbc:postgresql://localhost:5432/trade_center
      username: postgres
      password: password
      driverClassName: org.postgresql.Driver
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate.ddl-auto: validate

server.port: 9000

cache:
  tables:
    lifetime:
      max: 30000
      min: 2000
    timeouts:
      seance_info_flush: 3
  rps:
    lifetime: 120
    timeouts:
      cron_timeout: 3

# actuator
management:
  endpoints:
    web.base-path: /movie-park-service
    # web.exposure.include: *
  # HEALTH ENDPOINT
  endpoint:
    health.show-details: always
  health.diskSpace.enabled: false
